### ISSUE TITLE
没有生成 ClientServer 下 StartConfig 中的代码。

### ISSUE THREAD

**Issue by Lead-NorthStar** [EP-Toushirou/ET8-Luban#1]
![1818741480b0723464cccb54a5b0de02](https://github.com/EP-Toushirou/ET8-Luban/assets/139985926/59e2bd26-13a3-4e6b-be01-8441d9fab2a4)

**Comment by EP-Toushirou** [comment]
在ExcelExporter.cs里面有复制进去的，是点击Unity的按钮来使用的吗

**Comment by Lead-NorthStar** [comment]
是在Unity里点的按钮。其他地方复制的啊，那我先再看下代码，可能是我合并合出的问题

**Comment by Lead-NorthStar** [comment]
复制好像没有正常执行，感觉是这里的异步直接返回了，在代码还没要生成出来的时候，就已经拔后面的复制逻辑执行完了。我把这里这些代码注释掉后，复制才成功了。
![1b259f7967b2a973d4027e013d76e7c2](https://github.com/EP-Toushirou/ET8-Luban/assets/139985926/b7605911-e21b-495d-83c0-1f2db40f2f52)

**Comment by Lead-NorthStar** [comment]
也有可能是这里后续的代码没有执行，因为另一边的文件修改时间没有变过，也没有被删除

**Comment by Lead-NorthStar** [comment]
把 cs 目录下的文件删除后，执行生成后没有文件被复制进去

**Comment by EP-Toushirou** [comment]
嗯嗯 可以打印下 暂时身边没有电脑 确定的话也可以直接pr修复 麻烦了

**Comment by Lead-NorthStar** [comment]
我这边目前也是在用远程看了下。主要 mac 下目前直接无法执行指令，会报 bash: GenConfig.sh: command not found 的错，还没有找到解决办法。远程延迟太难受了。我这边先看能不能搞定这个吧

**Comment by EP-Toushirou** [comment]
好的 那过几天修复就好 mac运行就麻烦你了 我没有环境测试mac

**Comment by EP-Toushirou** [comment]
Close with [commit](https://github.com/EP-Toushirou/ET8-Luban/commit/4586d151c36a993ec1c35584e4d5c959adf872bf)
