### ISSUE TITLE
配置表间有引用的时候，好像会无法正常导出

### ISSUE THREAD

**Issue by Lead-NorthStar** [EP-Toushirou/ET8-Luban#2]
配置表间有引用的时候，好像会无法正常导出

有引用的表：
![image](https://github.com/EP-Toushirou/ET8-Luban/assets/139985926/f442cf43-695d-4b6a-a6b3-c822c55143b1)
tables 表：
![image](https://github.com/EP-Toushirou/ET8-Luban/assets/139985926/6fce1715-cb0d-4aa9-acd9-dcb29009abf8)
报错：
![b2362918e63e56700bfc15c423af9e08](https://github.com/EP-Toushirou/ET8-Luban/assets/139985926/b959e297-da56-46e6-b573-abb7d461a1c1)
改成这样就能正常导出了：
![image](https://github.com/EP-Toushirou/ET8-Luban/assets/139985926/9dd8a867-d76e-4e8c-9d3f-e65f8f1973ad)

**Comment by Lead-NorthStar** [comment]
感觉还是原来分开的模式好一些。

**Comment by Lead-NorthStar** [comment]
看起来 luban 好像不允许当前导出分组外的配置表使用 Ref

**Comment by Lead-NorthStar** [comment]
感觉还是以前分开的模式好一些

**Comment by EP-Toushirou** [comment]
我也发现了已经反馈到Luban项目:https://github.com/focus-creative-games/luban/issues/116

**Comment by EP-Toushirou** [comment]
> 感觉还是以前分开的模式好一些

如果没有Bug的话呢，是会造成其他体验下降吗，只是觉得以前那种文件太多而已

**Comment by Lead-NorthStar** [comment]
其他倒是没有什么其他问题了，我这边还没有深入使用。文件多也还好吧，毕竟这些文件变动也小。现在这个模式，加表就必须要多一步填写组了。
